DROP TABLE IF EXISTS ASSOCIAZIONECUCINE;
DROP TABLE IF EXISTS ACCOUNTFAMIGLIA;
DROP TABLE IF EXISTS BAMBINO;
DROP TABLE IF EXISTS UTENTECUCINA;

CREATE TABLE IF NOT EXISTS ACCOUNTFAMIGLIA(
	Email VARCHAR(100) PRIMARY KEY,
    Password VARCHAR(256) NOT NULL
);

CREATE TABLE IF NOT EXISTS BAMBINO(
	CodiceFiscale VARCHAR(17) PRIMARY KEY,
    EmailFamiglia VARCHAR(100) NOT NULL,
    Cognome VARCHAR(30),
    Nome VARCHAR(30),
    DataNascita DATE,
    FOREIGN KEY (EmailFamiglia) REFERENCES ACCOUNTFAMIGLIA(Email)
);

CREATE TABLE IF NOT EXISTS UTENTECUCINA(
	Username VARCHAR(20) PRIMARY KEY,
    Email VARCHAR(100),
    Password VARCHAR(256) NOT NULL
);

CREATE TABLE IF NOT EXISTS ASSOCIAZIONECUCINE(
	UsernameCucina VARCHAR(20),
    CodiceFiscaleBambino VARCHAR(17),
    FOREIGN KEY(CodiceFiscaleBambino) REFERENCES BAMBINO(CodiceFiscale),
    FOREIGN KEY(UsernameCucina) REFERENCES UTENTECUCINA(Username),
    PRIMARY KEY(UsernameCucina, CodiceFiscaleBambino)
);