DROP TABLE IF EXISTS ASSOCIAZIONECUCINE;
DROP TABLE IF EXISTS ACCOUNTFAMIGLIA;
DROP TABLE IF EXISTS BAMBINO;
DROP TABLE IF EXISTS UTENTECUCINA;
DROP TABLE IF EXISTS COMPOSIZIONEPIATTO;
DROP TABLE IF EXISTS COMPOSIZIONEALIMENTO;
DROP TABLE IF EXISTS INGREDIENTE;
DROP TABLE IF EXISTS ALIMENTO;
DROP TABLE IF EXISTS PIATTO;


CREATE TABLE IF NOT EXISTS INGREDIENTE(
	Id INTEGER PRIMARY KEY,
    Nome VARCHAR(30),
    Calorie INTEGER
);

CREATE TABLE IF NOT EXISTS ALIMENTO(
    Id INTEGER PRIMARY KEY,
    NOME VARCHAR(30)
);

CREATE TABLE IF NOT EXISTS COMPOSIZIONEALIMENTO(
	IdIngrediente INTEGER,
    IdAlimento INTEGER,
    FOREIGN KEY (IdAlimento) REFERENCES ALIMENTO(Id),
    FOREIGN KEY (IdIngrediente) REFERENCES INGREDIENTE(Id),
    PRIMARY KEY(IdIngrediente,IdAlimento)
);

CREATE TABLE IF NOT EXISTS PIATTO(
	Id INTEGER PRIMARY KEY,
    Nome VARCHAR(50),
    Descrizione VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS COMPOSIZIONEPIATTO(
	IdPiatto INTEGER,
    IdAlimento INTEGER,
    FOREIGN KEY (IdAlimento) REFERENCES ALIMENTO(Id),
    FOREIGN KEY (IdPiatto) REFERENCES PIATTO(Id),
    PRIMARY KEY(IdPiatto,IdAlimento)
);

CREATE TABLE IF NOT EXISTS ACCOUNTFAMIGLIA(
	Email VARCHAR(100) PRIMARY KEY,
    Password VARCHAR(256) NOT NULL
);

CREATE TABLE IF NOT EXISTS BAMBINO(
	CodiceFiscale VARCHAR(17) PRIMARY KEY,
    EmailFamiglia VARCHAR(100) NOT NULL,
    Cognome VARCHAR(30),
    Nome VARCHAR(30),
    DataNascita DATE,
    FOREIGN KEY (EmailFamiglia) REFERENCES ACCOUNTFAMIGLIA(Email)
);

CREATE TABLE IF NOT EXISTS UTENTECUCINA(
	Username VARCHAR(20) PRIMARY KEY,
    Email VARCHAR(100),
    Password VARCHAR(256) NOT NULL
);

CREATE TABLE IF NOT EXISTS ASSOCIAZIONECUCINE(
	UsernameCucina VARCHAR(20),
    CodiceFiscaleBambino VARCHAR(17),
    FOREIGN KEY(CodiceFiscaleBambino) REFERENCES BAMBINO(CodiceFiscale),
    FOREIGN KEY(UsernameCucina) REFERENCES UTENTECUCINA(Username),
    PRIMARY KEY(UsernameCucina, CodiceFiscaleBambino)
);