DROP TABLE IF EXISTS ASSOCIAZIONECUCINE;
DROP TABLE IF EXISTS BAMBINO;
DROP TABLE IF EXISTS UTENTECUCINA;
DROP TABLE IF EXISTS PIATTO;
DROP TABLE IF EXISTS MENU;
DROP TABLE IF EXISTS UTENTEAUSL;
DROP TABLE IF EXISTS COMPOSIZIONEMENU;
DROP TABLE IF EXISTS RICHIESTAMODIFICA;
DROP TABLE IF EXISTS MENUBAMBINO;


CREATE TABLE IF NOT EXISTS PIATTO(
	Id INTEGER PRIMARY KEY,
    Nome VARCHAR(50),
    Descrizione VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS BAMBINO(
	CodiceFiscale VARCHAR(17) PRIMARY KEY,
    Cognome VARCHAR(30),
    Nome VARCHAR(30),
    DataNascita DATE,
	Email VARCHAR(100),
	Password VARCHAR(128) NOT NULL
);

CREATE TABLE IF NOT EXISTS UTENTECUCINA(
	Username VARCHAR(20) PRIMARY KEY,
    Email VARCHAR(100),
    Password VARCHAR(128) NOT NULL
);

CREATE TABLE IF NOT EXISTS ASSOCIAZIONECUCINE(
	UsernameCucina VARCHAR(20),
    CodiceFiscaleBambino VARCHAR(17),
    FOREIGN KEY(CodiceFiscaleBambino) REFERENCES BAMBINO(CodiceFiscale),
    FOREIGN KEY(UsernameCucina) REFERENCES UTENTECUCINA(Username),
    PRIMARY KEY(UsernameCucina, CodiceFiscaleBambino)
);

CREATE TABLE IF NOT EXISTS UTENTEAUSL(
	Email VARCHAR(100) PRIMARY KEY,
	Password VARCHAR(128) NOT NULL
);

CREATE TABLE IF NOT EXISTS MENU(
	Id INTEGER PRIMARY KEY AUTO_INCREMENT,
	EmailCreatore VARCHAR(100),
	Nome VARCHAR(50),
	FOREIGN KEY(EmailCreatore) REFERENCES UTENTEAUSL(Email)
);

CREATE TABLE IF NOT EXISTS MENUBAMBINO(
	CodiceFiscaleBambino VARCHAR(17),
	IdMenu INTEGER,
	Stagione VARCHAR(15) NOT NULL,
	FOREIGN KEY(CodiceFiscaleBambino) REFERENCES BAMBINO(CodiceFiscale),
	FOREIGN KEY(IdMenu) REFERENCES MENU(Id),
	PRIMARY KEY(CodiceFiscaleBambino,IdMenu)
);

CREATE TABLE IF NOT EXISTS RICHIESTAMODIFICA(
	NumeroRichiesta INTEGER,
	CodiceFiscaleBambino VARCHAR(17),
	EmailUtenteAusl VARCHAR(100),
	IdMenu INTEGER,
	Data DATE NOT NULL,
	Approvato BOOLEAN NOT NULL,
	FOREIGN KEY(CodiceFiscaleBambino) REFERENCES MENUBAMBINO(CodiceFiscaleBambino),
	FOREIGN KEY(IdMenu) REFERENCES MENUBAMBINO(IdMenu),
	FOREIGN KEY(EmailUtenteAusl) REFERENCES UTENTEAUSL(Email),
	PRIMARY KEY(CodiceFiscaleBambino,IdMenu,NumeroRichiesta,EmailUtenteAusl)
);

CREATE TABLE IF NOT EXISTS COMPOSIZIONEMENU(
	IdMenu INTEGER,
	IdPiatto INTEGER,
	FOREIGN KEY(IdMenu) REFERENCES MENU(Id),
	FOREIGN KEY(IdPiatto) REFERENCES PIATTO(Id),
	PRIMARY KEY(IdMenu, IdPiatto)
);